// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PersistenceNoSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MongooseTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
var _entityInfo = (EntityInfo)Model;
            
            #line default
            #line hidden
            
            #line 3 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

    var allProperties = _entityInfo.AllProperties();

            
            #line default
            #line hidden
            this.Write("var mongoose = require(\'mongoose\');\r\nvar Schema = mongoose.Schema;\r\n");
            
            #line 8 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

    if(_entityInfo.References != null && _entityInfo.References.Count > 0)
    {
        foreach(var reference in _entityInfo.References)
        {

            
            #line default
            #line hidden
            this.Write("var ");
            
            #line 14 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema = require(\"");
            
            #line 14 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Model\").");
            
            #line 14 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema;\r\n");
            
            #line 15 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\nvar ");
            
            #line 20 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_entityInfo.Id)));
            
            #line default
            #line hidden
            this.Write("Schema = new Schema({\r\n");
            
            #line 21 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

    if(_entityInfo.Properties!=null && _entityInfo.Properties.Count>0)
    {
		var lastProperty = allProperties.Last();
        foreach(var property in  allProperties)
        {
            if(property.Equals(lastProperty))
            {
                if(_entityInfo.References != null && _entityInfo.References.Count > 0)
                {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 32 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 32 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(property.Type)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 33 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

                }else{

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 36 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 36 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(property.Type)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 37 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

                }
            }else{

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 41 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 41 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyType(property.Type)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 42 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

            }
        }
    }
    if(_entityInfo.References != null && _entityInfo.References.Count > 0)
    {
        var lastReference = _entityInfo.References.Last();
        foreach(var reference in _entityInfo.References)
        {
            if(reference.Equals(lastReference))
            {

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(reference.Id)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(reference.IsCollection){
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema]");
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
} else {
            
            #line default
            #line hidden
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 54 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 55 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

            }else{

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(reference.Id)));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(reference.IsCollection){
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema]");
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
} else {
            
            #line default
            #line hidden
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(reference.Type)));
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 58 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 59 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("});\r\n\r\nmodule.exports =  mongoose.model(\'");
            
            #line 66 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_entityInfo.Id)));
            
            #line default
            #line hidden
            this.Write("Model\', ");
            
            #line 66 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_entityInfo.Id)));
            
            #line default
            #line hidden
            this.Write("Schema);\r\nmodule.exports.");
            
            #line 67 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_entityInfo.Id)));
            
            #line default
            #line hidden
            this.Write("Schema =  ");
            
            #line 67 "D:\Working\Mobioos\Generators new changes\PersistenceNoSql\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(_entityInfo.Id)));
            
            #line default
            #line hidden
            this.Write("Schema;\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
