// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PersistenceNoSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MongoDBTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
var _entityInfo = (EntityInfo)Model;
            
            #line default
            #line hidden
            this.Write("db.createCollection(\"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\", {\n    validator: {\n        $jsonSchema: {\n            bsonType: \"object\",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

    if(_entityInfo.GetProperties() !=null && _entityInfo.GetProperties().Count() > 0)
    {
     var isRequiredList = _entityInfo.GetProperties().Where(p => p.IsRequired == true);
      if(isRequiredList.Count() > 0)
      {

            
            #line default
            #line hidden
            this.Write("\n            required:[\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

        int count = isRequiredList.Count() -1;
        int counter = 0;
        foreach(PropertyInfo property in isRequiredList)
        {
            if(property.IsRequired)
            {
                if(count == counter)
            {

            
            #line default
            #line hidden
            this.Write("\n                \"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\"\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

                }else{

            
            #line default
            #line hidden
            this.Write("\n                \"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

                }
            }
                     counter++;
        }

            
            #line default
            #line hidden
            this.Write("\n            ],\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

            }
    }
    if(_entityInfo.GetProperties() !=null && _entityInfo.GetProperties().Count() > 0)
    {

            
            #line default
            #line hidden
            this.Write("\n            properties:{\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

        int count = _entityInfo.GetProperties().Count() -1;
        int counter = 0;
        foreach(PropertyInfo property in _entityInfo.GetProperties())
        {

            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
var propertyType = Helper.GetType(property.Type);
            
            #line default
            #line hidden
            this.Write("\n                ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": {\n                    bsonType: \"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyType));
            
            #line default
            #line hidden
            this.Write("\",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

                if(property.Maximum > property.Minimum)
                {
                    if(propertyType == "int")
                    {

            
            #line default
            #line hidden
            this.Write("\n                    minimum: ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Minimum));
            
            #line default
            #line hidden
            this.Write(",\n                    maximum: ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Maximum));
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

                    }
                }
                if(count == counter)
                {

            
            #line default
            #line hidden
            this.Write("\n                }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

              }else{

            
            #line default
            #line hidden
            this.Write("\n                },\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

                }
                     counter++;
        }

            
            #line default
            #line hidden
            this.Write("\n            }\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongoDBTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\n        }\n    }\n})\n\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
