// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PersistenceNoSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Foundation.Jade.Models;
    using Common.Generator.Framework.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MongooseTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
var _entityInfo = (EntityInfo)Model;
            
            #line default
            #line hidden
            this.Write("var mongoose = require(\'mongoose\');\nvar Schema = mongoose.Schema;\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

        if(_entityInfo.GetProperties() !=null && _entityInfo.GetProperties().Count() > 0)
        {
            foreach(PropertyInfo property in _entityInfo.GetProperties())
            {
                if (property.Target != null && property.Type != null)
                {

            
            #line default
            #line hidden
            this.Write("\nvar ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema = require(\"");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelSuffix));
            
            #line default
            #line hidden
            this.Write("\").");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Type.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema;\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("\n\nvar ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema = new Schema({\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

    if(_entityInfo.GetProperties() !=null && _entityInfo.GetProperties().Count() > 0)
    {
    PropertyInfo last = _entityInfo.GetProperties().Last();
    foreach(PropertyInfo property in _entityInfo.GetProperties())
    {	
	 if (property.Equals(last))
     {

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(property.IsCollection){
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.GetType(property.Type)));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
} else {
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.GetType(property.Type)));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" \n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

		}
		else
		{

            
            #line default
            #line hidden
            this.Write("\n    ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Id.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(property.IsCollection){
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.GetType(property.Type)));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
} else {
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.GetType(property.Type)));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
if(Helper.IsModelBool(property.Type)){
            
            #line default
            #line hidden
            this.Write("Schema");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(",\n");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"

        }
	}
        }

            
            #line default
            #line hidden
            this.Write("\n});\n\nmodule.exports =  mongoose.model(\'");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_modelSuffix));
            
            #line default
            #line hidden
            this.Write("\', ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema);\nmodule.exports.");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema =  ");
            
            #line 1 "D:\Mobioos_Ver_2.0 --10.11.19\Generator-PersistenceDocumentDB-master\PersistenceNoSqlGenerator\GeneratorProject\Platforms\Backend\PersistenceNoSql\MongoDB\Templates\MongooseTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Schema;\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
